CREATE TABLE COUNTRIES (
  ISO CHAR(2),
  ISO3 CHAR(3),
  ISO_Code INT PRIMARY KEY,
  FIPS CHAR(2),
  Display_Name VARCHAR(50),
  Official_Name VARCHAR(100),
  Capital VARCHAR(50),
  Continent VARCHAR(50),
  Currency_Code CHAR(3),
  Currency_Name VARCHAR(50),
  Phone VARCHAR(70),
  Region_Code INT,
  Region_Name VARCHAR(50),
  Sub_Region_Code VARCHAR(10),
  Sub_Region_Name VARCHAR(50),
  Intermediate_Region_Code INT,
  Intermediate_Region_Name VARCHAR(50),
  Status VARCHAR(70),
  Developed_or_Developing VARCHAR(50),
  SIDS VARCHAR(10),
  LLDC VARCHAR(10),
  LDC VARCHAR(10),
  Area_Sq_Km INT,
  Population INT
);